name: nasa_apod_app
description: A new Flutter project that displays NASA's Astronomy Picture of the Day (APOD).

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cached_network_image: ^3.2.3

# This section is for dev dependencies, e.g., testing packages
dev_dependencies:
  flutter_test:
    sdk: flutter


# This section manages project versioning (major.minor.patch)
version: 1.0.0+1
environment:
  sdk: '^3.5.0'